#!/bin/bash 

ARRAY=(./bats_scripts/icommands.bats ./bats_scripts/icat_resource.bats  ./bats_scripts/useraccounts.bats ./bats_scripts/simple_group_tests.bats)

for FILE in ${ARRAY[@]};do
	echo $FILE
	bats $FILE
done
