#!/bin/bash 


ARRAY=( ./setup_3/resourcegroups_setup.bats ./setup_3/rules_setup.bats ./bats_scripts/replication.bats ./bats_scripts/trashcan.bats ./bats_scripts/useraccounts.bats  ./bats_scripts/multiple_users_groups.bats ./bats_scripts/permissions_set.bats ./bats_scripts/unicode.bats ./bats_scripts/quota_setup.bats ./bats_scripts/create_quotatestaccount2_ifiles.bats ./bats_scripts/setup_quotatestaccount2_authentication.bats ./bats_scripts/verify_quotas.bats ./bats_scripts/verify_quota_for_user.sh ./bats_scripts/create_quotatestaccount1_ifiles.bats ./bats_scripts/setup_quotatestaccount1_authentication.bats )

for FILE in ${ARRAY[@]};do
	bats $FILE
done
