#!/bin/bash 

bats ./bats_scripts/icommands.bats ./setup4/icat_resource.bats ./bats_scripts/useraccounts.bats ./bats_scripts/simple_group_tests.bats >> ~/logs/icat_v4_setup_test.log

cat ~/logs/icat_v4_setup_test.log | grep "not ok" && exit 1
