#!/bin/bash 


#bats ./bats_scripts/replication.bats
bats ./bats_scripts/trashcan.bats ./bats_scripts/useraccounts.bats  ./bats_scripts/multiple_users_groups.bats ./bats_scripts/permissions_set.bats ./bats_scripts/unicode.bats  | tee logs/v4_icat_tests
#./bats_scripts/verify_quotas.bats ./bats_scripts/verify_quota_for_user_v4.sh ./bats_scripts/verify_quota_for_group_v4.sh | tee logs/v4_icat_tests 
