#!/bin/bash 


ARRAY=(./bats_scripts/replication.bats ./bats_scripts/trashcan.bats ./bats_scripts/useraccounts.bats  ./bats_scripts/multiple_users_groups.bats ./bats_scripts/permissions_set.bats ./bats_scripts/unicode.bats  ./bats_scripts/verify_quotas.bats ./bats_scripts/verify_quota_for_user_v4.sh ./bats_scripts/verify_quota_for_group_v4.sh )
for FILE in ${ARRAY[@]};do
	printf "${GREEN}%*s\n" "${COLUMNS:-$(tput cols)}" '' | tr ' ' \#
	printf "${GREEN}%*s\n" "${COLUMNS:-$(tput cols)}" '' | tr ' ' \#
	bats $FILE
done
